name: Manual

on: 
  workflow_dispatch:
    inputs:
      image_name:
        description: "Image name"
        required: true
      host_name:
        description: "Host name"
        required: true
      first_user:
        description: "Name of the first user on the pi"
        required: true
        default: pi
      first_userpass:
        description: "Password of the first user on the pi. WARNING: Sensitive information, use with caution"
        required: true
        default: raspberry
      ssh_enabled:
        description: "1 if SSH should be enabled, 0 otherwise"
        required: true
        default: "1"
      wpa_ssid:
        description: "Wi-Fi SSID to connect automatically on first boot. WARNING: Sensitive information, use with caution"
        required: false
      wpa_passphrase:
        description: "Passphrase of Wi-Fi network to connect to. WARNING: Sensitive information, use with caution"
        required: false
      wpa_country:
        description: "ISO-3166-1 alpha-2 country code for the country this image will be used in (US, CA, GB, etc.)"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      
      - name: Build
        env:
          INPUT_IMAGE_NAME: ${{ github.event.inputs.image_name }}
          INPUT_HOSTNAME: ${{ github.event.inputs.host_name }}
          INPUT_FIRST_USER: ${{ github.event.inputs.first_user }}
          INPUT_FIRST_USERPASS: ${{ github.event.inputs.first_user_pass }}
          INPUT_SSH_ENABLED: ${{ github.event.inputs.ssh_enabled }}
          INPUT_WPA_SSID: ${{ github.event.inputs.wpa_ssid }}
          INPUT_WPA_PASSPHRASE: ${{ github.event.inputs.wpa_passphrase }}
          INPUT_WPA_COUNTRY: ${{ github.event.inputs.wpa_country }}

        run: |
          pushd pi-gen
          trap "popd; exit" INT TERM EXIT
          ./build-docker.sh -c ../config \
            IMAGE_NAME="${INPUT_IMAGE_NAME}" \
            HOSTNAME="${DFAULT_HOSTNAME}" \
            FIRST_USER="${INPUT_FIRST_USER}" \
            FIRST_USERPASS="${INPUT_FIRST_USERPASS}" \
            SSH_ENABLED="${INPUT_SSH_ENABLED}" \
            WPA_SSID="${INPUT_WPA_SSID}" \
            WPA_PASSPHRASE="${INPUT_WPA_PASSPHRASE}" \
            WPA_COUNTRY="${INPUT_WPA_COUNTRY}"

      - name: Upload artifacts  
        uses: actions/upload-artifact@v2
        with:
          name: "${{ github.event.inputs.image_name }}-${{ github.sha }}.zip"
          path: 'pi-gen/deploy/*.zip'